<?php 
if ($slides = $this->getSlider()->getSlides()) :

$slider = $this->getSlider();
$width = $slider['width'];
$height = $slider['height'];

$easyslide_id = $slider['easyslide_id'];

?>

<div class="easyslideslider-id" id="easyslideslider-<?php echo $easyslide_id; ?>" style='position: relative; <?php echo "width:".$width."px; height:".$height."px"; ?>'>
    <div class="scroller" style='<?php echo "width:".$width."px; height:".$height."px"; ?>'>
        <div class="content">
            <?php 
            $i = 0;
            foreach ($slides as $slide):
                echo '
                    <div class="section" id="section'.++$i.'">
                        <a href="'.$slide['target'].'">
                            <img src="'.$slide['url'].'" alt="" style="width:'.$width.'px; height:'.$height.'px" />
                            <p class="easyslidedescription">'.$slide['description'].'</p>
                        </a>
                    </div>';
            endforeach;
            ?>
        </div>
    </div>
    
    <div class="easyslidecontrolwr">
        <div class="easyslidercontrol">
        <?php if ($this->getSlider()->getControlsType() == 'number'): ?>
            <?php 
            $slcount = count($slides);
            for ($i = 0; $i < $slcount; $i++):
                echo '<a href="#section'.($i+1).'" title="Slide '.($i+1).'" class="easyslidedirect">'.($i+1).'</a>';
            endfor;
            ?>
        <?php else: ?>
            <a href="#" class="easyslideprev" title="Previous"></a>
            <a href="#" class="easyslidestop" title="Stop"></a>
            <a href="#" class="easyslideplay" title="Play"></a>
            <a href="#" class="easyslidenext" title="Next"></a>
        <?php endif; ?>
        </div>
    </div>
</div>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl();?>css/easyslide.css" />
<script src="<?php echo $this->getSkinUrl();?>js/easyslide.js" type="text/javascript"></script>
<script type="text/javascript" charset="utf-8">
//<![CDATA[ 
    var new_glider = new Glider('easyslideslider-<?php echo $easyslide_id; ?>', {
        duration: <?php echo $slider['duration'];?>,
        autoGlide: <?php echo (int)$slider['autoglide'];?>,
        frequency: <?php echo $slider['frequency'];?>,
        initialSection: 'section1'
    });
//]]> 
</script>

<?php endif; ?>
